use WebStore;

/*Задача 1*/
SELECT OFFICE, CITY, MGR 
FROM OFFICES 
WHERE SALES > 350000.00;

/*Задача 2.1*/
SELECT * FROM ORDERS 
WHERE ORDER_DATE NOT BETWEEN '20080101' AND '20081231' AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%');

/*Задача 2.2*/
SELECT MFR, SUM (AMOUNT) AS 'SUM_AMOUNT' 
FROM ORDERS 
WHERE ORDER_DATE NOT BETWEEN '20080101' AND '20081231'
AND PRODUCT LIKE '%0%'
GROUP BY MFR 
ORDER BY 'SUM_AMOUNT';

/*Задача 2.3*/
SELECT TOP 1 WITH TIES MFR, SUM (AMOUNT) AS 'SUM_AMOUNT' 
FROM ORDERS 
WHERE ORDER_DATE NOT BETWEEN '20080101' AND '20081231'
AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY MFR 
ORDER BY 'SUM_AMOUNT'
;


/*Задача 3*/
SELECT TOP 1 WITH TIES REP_OFFICE, COUNT(*) AS 'COUT_OFFICE'  
FROM SALESREPS 
WHERE TITLE IN ('Sales Rep') 
AND (AGE = 29 OR AGE = 45 OR AGE = 48)
GROUP BY REP_OFFICE ORDER BY 'COUT_OFFICE' DESC;

/*Задача 4*/
SELECT TOP 1 WITH TIES MFR_ID, PRODUCT_ID, DESCRIPTION, LEN (DESCRIPTION) AS 'LEN_DESCRIPTION'  
FROM PRODUCTS 
GROUP BY MFR_ID, PRODUCT_ID, DESCRIPTION
ORDER BY 'LEN_DESCRIPTION' DESC;

/*Задача 5*/
SELECT DISTINCT UPPER(CONCAT_WS ('_',RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM(DESCRIPTION))),LEN(CONCAT_WS ('_',RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM(DESCRIPTION))) AS 'LEN_Conc'
FROM PRODUCTS 
WHERE MFR_ID NOT LIKE ('')
GROUP BY MFR_ID, PRODUCT_ID, DESCRIPTION
ORDER BY 'LEN_Conc' DESC;

/*Задача 6*/

SELECT TOP 1 WITH TIES CUST_NUM, CONCAT(SUBSTRING(COMPANY,1,2), REPLICATE('*', LEN(COMPANY) - 4),SUBSTRING(COMPANY,LEN(COMPANY) - 2,2)), CREDIT_LIMIT
FROM CUSTOMERS
ORDER BY CREDIT_LIMIT
;

