use WebStore;
/*Завдання 1 */
SELECT EMPL_NUM, NAME, AGE, TITLE FROM SALESREPS WHERE AGE>45 ORDER BY AGE DESC;

/*Завдання 2 */
SELECT DISTINCT MFR, PRODUCT FROM ORDERS WHERE ORDER_DATE BETWEEN '20080101' AND '20081231' ;

/*Завдання 3*/
SELECT TOP 1 WITH TIES REP, COUNT(ORDER_NUM) AS order_count 
FROM ORDERS 
WHERE ORDER_DATE BETWEEN '20080101' AND '20081231' 
GROUP BY REP 
ORDER BY order_count DESC;

